# render.yaml
services:
  - type: web
    name: alx_travel_tee
    env: python
    plan: free
    region: Kenya # change if you prefer another region
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn alx_travel_app_0x03.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        fromDatabase: secret_key  # or manually set value
      - key: DB_NAME
        value: alx_travel_app
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        value: 1711
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_PORT
        value: "5432"
      - key: REDIS_URL
        value: redis://your_redis_url:6379

databases:
  - name: alx_travel_app
    type: postgresql
    plan: free
    region: Kenya

addons:
  - type: redis
    name: alx-travel-redis
    plan: free
    region: kenya
